version: "3.7"

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}_${NODE_ENV}
    volumes:
      - sysvac:/var/lib/postgres/data
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  sysvac: {}